
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.sintactic;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int NUMERO = 60;
  public static final int MAIGUAL = 40;
  public static final int CONST = 8;
  public static final int CHAR = 5;
  public static final int MEIGUAL = 42;
  public static final int OUTPUT = 26;
  public static final int INPUT = 25;
  public static final int XOR = 47;
  public static final int CASE = 19;
  public static final int ELEMENTO = 59;
  public static final int RESTA = 29;
  public static final int LPAREN = 48;
  public static final int COND = 36;
  public static final int REPEAT = 16;
  public static final int DECR = 34;
  public static final int LCORCH = 50;
  public static final int INT = 2;
  public static final int INCR = 33;
  public static final int ARRAY = 21;
  public static final int FOR = 14;
  public static final int RPAREN = 49;
  public static final int RCORCH = 51;
  public static final int AND = 45;
  public static final int NOT = 44;
  public static final int IGUAL = 38;
  public static final int OR = 46;
  public static final int BOOL = 4;
  public static final int DIV = 31;
  public static final int UNTIL = 17;
  public static final int SUMA = 28;
  public static final int MAIN = 11;
  public static final int IF = 12;
  public static final int ID = 58;
  public static final int DECIMAL = 61;
  public static final int DIST = 39;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int COMA = 55;
  public static final int CADENA = 57;
  public static final int MENOR = 43;
  public static final int MOD = 32;
  public static final int BREAK = 20;
  public static final int LBRACK = 52;
  public static final int SWITCH = 18;
  public static final int MAYOR = 41;
  public static final int ELSE = 13;
  public static final int PUNTO = 54;
  public static final int VACIO = 7;
  public static final int RBRACK = 53;
  public static final int WHILE = 15;
  public static final int ACCESO = 23;
  public static final int DPUNTO = 56;
  public static final int FLOAT = 3;
  public static final int OUTPUTN = 27;
  public static final int ASIGN = 37;
  public static final int PROD = 30;
  public static final int LONG = 22;
  public static final int STRING = 6;
  public static final int FALSE = 10;
  public static final int MODIF = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "VACIO",
  "CONST",
  "TRUE",
  "FALSE",
  "MAIN",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "REPEAT",
  "UNTIL",
  "SWITCH",
  "CASE",
  "BREAK",
  "ARRAY",
  "LONG",
  "ACCESO",
  "RETURN",
  "INPUT",
  "OUTPUT",
  "OUTPUTN",
  "SUMA",
  "RESTA",
  "PROD",
  "DIV",
  "MOD",
  "INCR",
  "DECR",
  "MODIF",
  "COND",
  "ASIGN",
  "IGUAL",
  "DIST",
  "MAIGUAL",
  "MAYOR",
  "MEIGUAL",
  "MENOR",
  "NOT",
  "AND",
  "OR",
  "XOR",
  "LPAREN",
  "RPAREN",
  "LCORCH",
  "RCORCH",
  "LBRACK",
  "RBRACK",
  "PUNTO",
  "COMA",
  "DPUNTO",
  "CADENA",
  "ID",
  "ELEMENTO",
  "NUMERO",
  "DECIMAL"
  };
}

